word_list = [
    "python", "java", "kotlin", "javascript", "hangman", "programming", "developer",
    "algorithm", "function", "variable", "syntax", "compiler", "debugger", "runtime",
    "hardware", "software", "database", "network", "internet", "protocol", "encryption",
    "framework", "library", "interface", "inheritance", "polymorphism", "abstraction",
    "encapsulation", "constructor", "exception", "iteration", "recursion", "binary",
    "hexadecimal", "array", "linkedlist", "stack", "queue", "hashtable", "dictionary",
    "tuple", "boolean", "string", "integer", "float", "class", "object", "method",
    "attribute", "module", "package", "import", "export", "argument", "parameter",
    "lambda", "closure", "decorator", "generator", "comprehension", "context",
    "manager", "virtual", "machine", "cloud", "server", "client", "frontend",
    "backend", "fullstack", "responsive", "design", "version", "control", "git",
    "repository", "commit", "branch", "merge", "conflict", "pull", "push", "clone",
    "fork", "issue", "bug", "feature", "release", "deploy", "testing", "coverage",
    "automation", "continuous", "integration", "delivery", "deployment", "pipeline",
    "agile", "scrum", "kanban", "waterfall", "methodology", "sprint", "task",
    "story", "epic", "backlog", "retrospective", "planning", "meeting", "standup",
    "daily", "review", "release", "candidate", "production", "environment",
    "staging", "development", "testing", "build", "compile", "execute", "runtime",
    "error", "syntax", "logical", "semantic", "debug", "trace", "breakpoint",
    "watch", "step", "inspect", "profile", "optimize", "performance", "memory",
    "leak", "overflow", "underflow", "thread", "process", "concurrency", "parallelism",
    "asynchronous", "synchronous", "callback", "promise", "future", "async", "await",
    "event", "loop", "handler", "listener", "signal", "slot", "stream", "buffer",
    "block", "sector", "partition", "filesystem", "directory", "path", "file",
    "read", "write", "open", "close", "delete", "rename", "copy", "move", "sync",
    "backup", "restore", "snapshot", "replication", "sharding", "partitioning",
    "scaling", "load", "balancing", "distributed"]
